#!/usr/bin/env python3
"""Generate a compact 1-bit Hangul bitmap font header for the e-ink firmware."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


HANGUL_START = 0xAC00
HANGUL_COUNT = 11172


def glyph_bytes(font: ImageFont.FreeTypeFont, codepoint: int, size: int, threshold: int) -> bytes:
    text = chr(codepoint)
    image = Image.new("L", (size, size), 0)
    draw = ImageDraw.Draw(image)
    bbox = draw.textbbox((0, 0), text, font=font)
    glyph_w = bbox[2] - bbox[0]
    glyph_h = bbox[3] - bbox[1]
    x = max(0, (size - glyph_w) // 2 - bbox[0])
    y = max(0, (size - glyph_h) // 2 - bbox[1])
    draw.text((x, y), text, font=font, fill=255)

    packed = bytearray()
    for row in range(size):
        byte = 0
        bit = 7
        for col in range(size):
            if image.getpixel((col, row)) >= threshold:
                byte |= 1 << bit
            bit -= 1
            if bit < 0:
                packed.append(byte)
                byte = 0
                bit = 7
        if bit != 7:
            packed.append(byte)
    return bytes(packed)


def write_header(font_path: Path, output_path: Path, size: int, threshold: int, symbol_prefix: str) -> None:
    font = ImageFont.truetype(str(font_path), size)
    bytes_per_row = (size + 7) // 8
    bytes_per_glyph = bytes_per_row * size
    prefix = symbol_prefix.upper()

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as out:
        out.write("// Generated by tools/fonts/generate_nanum_bitmap_font.py\n")
        out.write("// Source font: NanumGothicCoding, Open Font License.\n")
        out.write("#pragma once\n\n")
        out.write("#include <Arduino.h>\n\n")
        out.write(f"static constexpr uint16_t {prefix}_HANGUL_START = 0x{HANGUL_START:04X};\n")
        out.write(f"static constexpr uint16_t {prefix}_HANGUL_COUNT = {HANGUL_COUNT};\n")
        out.write(f"static constexpr uint8_t {prefix}_GLYPH_SIZE = {size};\n")
        out.write(f"static constexpr uint8_t {prefix}_GLYPH_BYTES_PER_ROW = {bytes_per_row};\n")
        out.write(f"static constexpr uint8_t {prefix}_GLYPH_BYTES = {bytes_per_glyph};\n\n")
        out.write(f"static const uint8_t {prefix}_HANGUL_BITMAPS[] PROGMEM = {{\n")

        line = "  "
        for index in range(HANGUL_COUNT):
            data = glyph_bytes(font, HANGUL_START + index, size, threshold)
            for value in data:
                token = f"0x{value:02X},"
                if len(line) + len(token) + 1 > 118:
                    out.write(line.rstrip() + "\n")
                    line = "  "
                line += token + " "
        if line.strip():
            out.write(line.rstrip() + "\n")
        out.write("};\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--size", default=18, type=int)
    parser.add_argument("--threshold", default=96, type=int)
    parser.add_argument("--symbol-prefix", default="NANUM")
    args = parser.parse_args()
    write_header(args.font, args.output, args.size, args.threshold, args.symbol_prefix)


if __name__ == "__main__":
    main()
