[platformio]
default_envs = seeed_xiao_esp32s3

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_unflags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
build_flags =
  -DARDUINO_USB_MODE=0
  -DARDUINO_USB_CDC_ON_BOOT=0
lib_deps =
  zinggjm/GxEPD2
  bblanchon/ArduinoJson
  olikraus/U8g2_for_Adafruit_GFX
  h2zero/NimBLE-Arduino@^1.4.3
  ricmoo/QRCode@^0.0.1
